.selenium-test: &selenium-test
  stage: test
  image: yourlabs/python
  script:
  - pacman -Sy --noconfirm firefox geckodriver
  - pip install -e .[test]
  - pip install https://github.com/pytest-dev/pytest-splinter/archive/master.tar.gz
  - python serve.py &
  - py.test -sv --splinter-headless

selenium-test:
  <<: *selenium-test

pages:
  stage: deploy
  image: node:alpine
  script:
  - sed -i 's@<head>@<head><base href="/autocomplete-light/">@' index.html
  - mkdir public
  - mv index.html public/
  - cp autocomplete_light/static/autocomplete_light/autocomplete-light.{js,css} public/
  artifacts:
    paths:
    - public
  when: manual
  only:
    refs:
      - master
